"""Add answers column to Claim model

Revision ID: cc8a4df4d770
Revises: aa9477ebdf48
Create Date: 2025-01-18 01:04:40.774967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8a4df4d770'
down_revision = 'aa9477ebdf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.Text(), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('claim_date')
        batch_op.drop_column('claimed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('claim_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('answers')

    # ### end Alembic commands ###
