"""Add claimed_by and claim_date columns

Revision ID: aa9477ebdf48
Revises: 
Create Date: 2025-01-18 00:46:30.992414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9477ebdf48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claim_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('claim_date')
        batch_op.drop_column('claimed_by')

    # ### end Alembic commands ###
